### ISSUE TITLE
Sample Android app with API < 26 results in crash. 

### ISSUE THREAD

**Issue by QuincyAtCapgemini** [usabilla/usabilla-u4a-xamarin#64]
When using the Usabilla Sample App on a device with an API level lower than 26, the app fails on AppStart.

---

**Steps to reproduce**

- Create an emulator or use a device with API level 25 or lower
- Run Xamarin.Usabilla.Sample.Android
- Application crashes on AppStart.

---

**Exception:** 

{class java.lang.ClassNotFoundException}	Java.Lang.Class

Didn't find class "java.time.OffsetDateTime" on path: DexPathList[[zip file "/data/app/com.usabilla.usabilla_xamarin-1/base.apk"],nativeLibraryDirectories=[/data/app/com.usabilla.usabilla_xamarin-1/lib/x86, /data/app/com.usabilla.usabilla_xamarin-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]

---

**StackTrace:**
`  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <1959115d56f8444789986cf39185638c>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <1959115d56f8444789986cf39185638c>:0 
  at UsabillaAndroid.Usabilla.set_DebugEnabled (System.Boolean value) [0x0001a] in /Users/ademirsoy/Documents/Development/xamarin/usabilla-u4a-xamarin/UsabillaBindings/Xamarin.Usabilla.Android/obj/Debug/generated/src/UsabillaAndroid.Usabilla.cs:96 
  at Xamarin.Usabilla.UsabillaXamarin.set_DebugEnabled (System.Boolean value) [0x00000] in /Users/ademirsoy/Documents/Development/xamarin/usabilla-u4a-xamarin/UsabillaBindings/Xamarin.Usabilla.Android/Xamarin.Usabilla.Android/UsabillaXamarin.cs:134 
  at Xamarin.Usabilla.Sample.App..ctor () [0x0000f] in /Users/user/Downloads/usabilla-u4a-xamarin-master/UsabillaBindings/Xamarin.Usabilla.Sample/App.xaml.cs:14 
  at Xamarin.Usabilla.Sample.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0003b] in /Users/user/Downloads/usabilla-u4a-xamarin-master/UsabillaBindings/Xamarin.Usabilla.Sample.Android/MainActivity.cs:25 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00010] in /Users/builder/azdo/_work/2/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Android.App.Activity.cs:2691 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
  --- End of managed Java.Lang.NoClassDefFoundError stack trace ---
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/OffsetDateTime;
	at com.usabilla.sdk.ubform.utils.DateUtilsKt.getDateFromMilliseconds$default(DateUtils.kt:9)
	at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.record(ReleaseTelemetryRecorder.kt:90)
	at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.start(ReleaseTelemetryRecorder.kt:16)
	at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.startAndStop(ReleaseTelemetryRecorder.kt:23)
	at com.usabilla.sdk.ubform.UsabillaInternal.setDebugEnabled(UsabillaInternal.kt:112)
	at com.usabilla.sdk.ubform.Usabilla.setDebugEnabled(Usabilla.kt:22)
	at crc64f4fd58fa4a919736.MainActivity.n_onCreate(Native Method)
	at crc64f4fd58fa4a919736.MainActivity.onCreate(MainActivity.java:37)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.OffsetDateTime" on path: DexPathList[[zip file "/data/app/com.usabilla.usabilla_xamarin-1/base.apk"],nativeLibraryDirectories=[/data/app/com.usabilla.usabilla_xamarin-1/lib/x86, /data/app/com.usabilla.usabilla_xamarin-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 20 more
`

**Comment by eduakaszas** [comment]
Hi @QuincyAtCapgemini, 

Thank you for reaching out. 

The issue you're running into is caused by our SDK targeting Java 8 and using a Java 8 class (OffsetDateTime). We have [a section in the documentation of our native SDK](https://github.com/usabilla/usabilla-u4a-android-sdk#java-8) that addresses it, however, we'll look into how we could solve this for the Xamarin wrapper specifically. 

In the meantime, if you'd like to help us fix this issue, you could also potentially contribute to it, considering our project is open source. Feel free to open a PR in case you have any suggestions. 

Kind regards, 
Édua

**Comment by eduakaszas** [comment]
Hi @QuincyAtCapgemini , 

Thank you for your patience.

As per the latest release, this issue can be solved by using the desugaring library mentioned in our Readme [here](https://github.com/usabilla/usabilla-u4a-xamarin#installation).

I hope this helps but let us know if you're still encountering issues. 

Kind regards, 
Édua
